
// Generated by gen_design.py from UnifiedSingleExposerKeyMngrTb.txt
// Expects mkCombinedIOCapExposerV6_blockinvalid_2pool_1percycle_KeyManager2V1_Tb to fit the UnifiedSingleExposerKeyMngrTb Bluespec interface
module mkCombinedIOCapExposerV6_blockinvalid_2pool_1percycle_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design(
    input CLK_SLOW,
    input CLK_FAST,
    input RST_N,
    input pin_in,
    output pin_out
);
    wire[365-1:0] dut_in;
    wire[1024-1:0] dut_out;
    assign dut_out[1023:862] = 0;
    
    input_harness#(.BITS(365)) i(
        .slow_clk(CLK_SLOW),
        .fast_clk(CLK_FAST),
        .rst_n(RST_N),
        .pin_on_slow_clk(pin_in),
        .data_on_fast_clk(dut_in)
    );

    output_harness#(.BITS(1024), .LG_BITS(10)) o(
        .slow_clk(CLK_SLOW),
        .fast_clk(CLK_FAST),
        .rst_n(RST_N),
        .data_on_fast_clk(dut_out),
        .pin_on_slow_clk(pin_out)
    );

    mkCombinedIOCapExposerV6_blockinvalid_2pool_1percycle_KeyManager2V1_Tb dut(
        .CLK(CLK_FAST),
        .RST_N(RST_N),

        .keyStore_ar_put_val(dut_in[15:0]),
        .keyStore_aw_put_val(dut_in[31:16]),
        .keyStore_w_put_val(dut_in[67:32]),
        .exposer4x32_iocapsIn_axiSignals_w_put_val(dut_in[104:68]),
        .exposer4x32_sanitizedOut_r_put_val(dut_in[143:105]),
        .exposer4x32_sanitizedOut_b_put_val(dut_in[149:144]),
        .exposer4x32_iocapsIn_axiSignals_ar_put_val(dut_in[249:150]),
        .exposer4x32_iocapsIn_axiSignals_aw_put_val(dut_in[349:250]),
        .EN_exposer4x32_iocapsIn_axiSignals_ar_put(dut_in[350]),
        .EN_exposer4x32_iocapsIn_axiSignals_aw_put(dut_in[351]),
        .EN_exposer4x32_iocapsIn_axiSignals_b_drop(dut_in[352]),
        .EN_exposer4x32_iocapsIn_axiSignals_r_drop(dut_in[353]),
        .EN_exposer4x32_iocapsIn_axiSignals_w_put(dut_in[354]),
        .EN_exposer4x32_sanitizedOut_ar_drop(dut_in[355]),
        .EN_exposer4x32_sanitizedOut_aw_drop(dut_in[356]),
        .EN_exposer4x32_sanitizedOut_b_put(dut_in[357]),
        .EN_exposer4x32_sanitizedOut_r_put(dut_in[358]),
        .EN_exposer4x32_sanitizedOut_w_drop(dut_in[359]),
        .EN_keyStore_ar_put(dut_in[360]),
        .EN_keyStore_aw_put(dut_in[361]),
        .EN_keyStore_b_drop(dut_in[362]),
        .EN_keyStore_r_drop(dut_in[363]),
        .EN_keyStore_w_put(dut_in[364]),
        .keyStore_b_peek(dut_out[1:0]),
        .keyStore_r_peek(dut_out[35:2]),
        .exposer4x32_sanitizedOut_w_peek(dut_out[72:36]),
        .exposer4x32_iocapsIn_axiSignals_r_peek(dut_out[111:73]),
        .exposer4x32_iocapsIn_axiSignals_b_peek(dut_out[117:112]),
        .debugKeyState__read(dut_out[629:118]),
        .exposer4x32_sanitizedOut_ar_peek(dut_out[726:630]),
        .exposer4x32_sanitizedOut_aw_peek(dut_out[823:727]),
        .exposer4x32_iocapsIn_axiSignals_ar_canPut(dut_out[824]),
        .exposer4x32_iocapsIn_axiSignals_aw_canPut(dut_out[825]),
        .exposer4x32_iocapsIn_axiSignals_b_canPeek(dut_out[826]),
        .exposer4x32_iocapsIn_axiSignals_r_canPeek(dut_out[827]),
        .exposer4x32_iocapsIn_axiSignals_w_canPut(dut_out[828]),
        .exposer4x32_sanitizedOut_ar_canPeek(dut_out[829]),
        .exposer4x32_sanitizedOut_aw_canPeek(dut_out[830]),
        .exposer4x32_sanitizedOut_b_canPut(dut_out[831]),
        .exposer4x32_sanitizedOut_r_canPut(dut_out[832]),
        .exposer4x32_sanitizedOut_w_canPeek(dut_out[833]),
        .keyStore_ar_canPut(dut_out[834]),
        .keyStore_aw_canPut(dut_out[835]),
        .keyStore_b_canPeek(dut_out[836]),
        .keyStore_r_canPeek(dut_out[837]),
        .keyStore_w_canPut(dut_out[838]),
        .RDY_debugKeyState__read(dut_out[839]),
        .RDY_exposer4x32_iocapsIn_axiSignals_ar_put(dut_out[840]),
        .RDY_exposer4x32_iocapsIn_axiSignals_aw_put(dut_out[841]),
        .RDY_exposer4x32_iocapsIn_axiSignals_b_drop(dut_out[842]),
        .RDY_exposer4x32_iocapsIn_axiSignals_b_peek(dut_out[843]),
        .RDY_exposer4x32_iocapsIn_axiSignals_r_drop(dut_out[844]),
        .RDY_exposer4x32_iocapsIn_axiSignals_r_peek(dut_out[845]),
        .RDY_exposer4x32_iocapsIn_axiSignals_w_put(dut_out[846]),
        .RDY_exposer4x32_sanitizedOut_ar_drop(dut_out[847]),
        .RDY_exposer4x32_sanitizedOut_ar_peek(dut_out[848]),
        .RDY_exposer4x32_sanitizedOut_aw_drop(dut_out[849]),
        .RDY_exposer4x32_sanitizedOut_aw_peek(dut_out[850]),
        .RDY_exposer4x32_sanitizedOut_b_put(dut_out[851]),
        .RDY_exposer4x32_sanitizedOut_r_put(dut_out[852]),
        .RDY_exposer4x32_sanitizedOut_w_drop(dut_out[853]),
        .RDY_exposer4x32_sanitizedOut_w_peek(dut_out[854]),
        .RDY_keyStore_ar_put(dut_out[855]),
        .RDY_keyStore_aw_put(dut_out[856]),
        .RDY_keyStore_b_drop(dut_out[857]),
        .RDY_keyStore_b_peek(dut_out[858]),
        .RDY_keyStore_r_drop(dut_out[859]),
        .RDY_keyStore_r_peek(dut_out[860]),
        .RDY_keyStore_w_put(dut_out[861])
    );
endmodule

