default:
    @just --list

gen ifc blu_design mhz:
    # Make the verilog, which ensures all the relevant files exist for the project generator
    (cd ../ && make ./build/verilog/{{blu_design}}.v)
    # Make the working directory for quartus
    uv run python3 gen_design.py {{ifc}} {{blu_design}} {{mhz}}

gen-all: \
    (gen "SimpleIOCapExposerKeyMngrV2Tb.txt" "mkSimpleIOCapExposerV6_blockinvalid_1percycle_Tb" "500") \
    (gen "SimpleIOCapExposerKeyMngrV2Tb.txt" "mkSimpleIOCapExposerV6_blockinvalid_Tb" "500") \
    (gen "SimpleIOCapExposerKeyMngrV2Tb.txt" "mkSimpleIOCapExposerV6_blockinvalid_1percycle_Tb" "200") \
    (gen "SimpleIOCapExposerKeyMngrV2Tb.txt" "mkSimpleIOCapExposerV6_blockinvalid_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_1percycle_KeyManager2V1_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_0pool_KeyManager2V1_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_1pool_1percycle_KeyManager2V1_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_2pool_1percycle_KeyManager2V1_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_3pool_1percycle_KeyManager2V1_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_4pool_1percycle_KeyManager2V1_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_1pool_2percycle_KeyManager2V1_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_2pool_2percycle_KeyManager2V1_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_3pool_2percycle_KeyManager2V1_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_4pool_2percycle_KeyManager2V1_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_5pool_2percycle_KeyManager2V1_Tb" "200") \
    (gen "SingleChecker3.txt" "mkSingleChecker3_1percycle" "200") \
    (gen "SingleChecker3.txt" "mkSingleChecker3_2percycle" "200") \
    (gen "SingleChecker3.txt" "mkSingleChecker3_1percycle" "300") \
    (gen "SingleChecker3.txt" "mkSingleChecker3_2percycle" "300")

resynth-paper-reports:
    just projects/mkSingleChecker3_1percycle_SingleChecker3_design_300MHz/synth
    just projects/mkSingleChecker3_2percycle_SingleChecker3_design_300MHz/synth
    just projects/mkCombinedIOCapExposerV6_0pool_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design_200MHz/synth
    just projects/mkCombinedIOCapExposerV6_blockinvalid_1pool_2percycle_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design_200MHz/synth
    just projects/mkCombinedIOCapExposerV6_blockinvalid_2pool_2percycle_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design_200MHz/synth
    just projects/mkCombinedIOCapExposerV6_blockinvalid_3pool_2percycle_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design_200MHz/synth
    just projects/mkCombinedIOCapExposerV6_blockinvalid_4pool_2percycle_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design_200MHz/synth
    just projects/mkCombinedIOCapExposerV6_blockinvalid_5pool_2percycle_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design_200MHz/synth

regen-paper-reports:
    uv run python3 gen_report.py ./results/ ./hardware_synths.toml