default:
    @just --list

gen ifc blu_design mhz:
    # Make the verilog
    (cd ../ && make ./build/verilog/{{blu_design}}.v)
    # Make the working directory for quartus
    python3 gen_design.py {{ifc}} {{blu_design}} {{mhz}}

gen-all: \
    (gen "SimpleIOCapExposerKeyMngrV2Tb.txt" "mkSimpleIOCapExposerV6_blockinvalid_1percycle_Tb" "500") \
    (gen "SimpleIOCapExposerKeyMngrV2Tb.txt" "mkSimpleIOCapExposerV6_blockinvalid_Tb" "500")
