= DE10Pro-cheri-bgas Bluespec folder

:toc: macro
:toclevels: 4
:toc-title:
:toc-placement!:
:source-highlighter:

This folder contains the following submodules

- https://github.com/POETSII/DE10Pro-bsv-shell[DE10Pro-bsv-shell]
- https://github.com/CTSRD-CHERI/Toooba[Toooba]
- https://github.com/CTSRD-CHERI/Recipe[Recipe]

as well as some "toplevel glue" for the CHERI BGAS system.

[discrete]
== Contents

toc::[]

:sectnums:

== Toplevel structure

The
https://github.com/CTSRD-CHERI/DE10Pro-cheri-bgas/blob/main/bluespec/CHERI_BGAS_Top.bsv[CHERI_BGAS_Top.bsv]
file is the toplevel file for the CHERI-BGAS system. It defines a
`mkCHERI_BGAS_Top` bluespec module which provides an interface defined by the
general https://github.com/POETSII/DE10Pro-bsv-shell[DE10Pro-bsv-shell] project.
It basically consists in:

- a "h2f_lw" AXI4Lite subordinate port for "control" traffic from the HPS system
- a "h2f" AXI4 subordinate port for general traffic from the HPS system
- a "f2h" AXI4 manager port for general traffic to the HPS system
- three "ddr{b, c, d}" AXI4 manager ports for DDR memory traffic
- a vector of 32 interrupt sources

Within `mkCHERI_BGAS_Top`, a Toooba core is instantiated and its two manager
ports are connected to 4 subordinates at the moment:

- the DDRB channel
- a https://github.com/CTSRD-CHERI/BlueStuff/blob/master/AXI4_Fake_16550.bsv[fake 16550]
- a place holder "bootrom" (currently always returning `0`)
- the "f2h" channel

The memory map is defined in
https://github.com/CTSRD-CHERI/DE10Pro-cheri-bgas/blob/main/bluespec/SoC_Map.bsv[SoC_Map.bsv].

The "h2f_lw" port exposes the core's AXI4Lite port providing access to a debug
unit. It adds a fake 16550 interface facing the HPS system as the other end of
the one previously mentioned already exposed to the RISC-V core. It also exposes
a mechanism to trigger interrupts on the RISC-V core, and a mechanism to set the
upper 32-bits of the memory requests performed via the "h2f" port.

The specific AXI4Lite offsets are currently as follows:

- `0x0000_0000 -> 0x0000_0fff`: Debug Unit
+
See https://github.com/CTSRD-CHERI/Toooba/blob/wip-aj443-WindCoreInterface/src_Core/Debug_Module/README.txt[here]
for further details on the register interface layout.
- `0x0000_1000 -> 0x0000_1fff`: Interrupt lines
+
Reads to this device return a `SLVERR`. Writes behave as follows:
+
* 32-bit offset 0 - byte offset 0x0000:
  set irq lines that correspond to high bits in the written data
* 32-bit offset 1 - byte offset 0x0004:
  clear irq lines that correspond to high bits in the written data
* 32-bit offset 2 - byte offset 0x0008:
  set nmirq lines that correspond to high bits in the written data
* 32-bit offset 3 - byte offset 0x000c:
  clear nmirq lines that correspond to high bits in the written data

+
See the definition of `mkIrqAXI4Lite_Subordinate` in
https://github.com/CTSRD-CHERI/WindCoreInterface/blob/main/WindCoreUtils.bsv[WindCoreUtils.bsv].
Currently, of the 32 interrupt lines to the riscv core exposed here, line 0 is
reserved for the internal 16550 interrupt. Bit 0 of the written data is
therefore ignored. Bit 1 to 31 correspond to the remaining interrupt lines.
- `0x0000_2000 -> 0x0000_2fff`: Others
+
Not currently in use
- `0x0000_3000 -> 0x0000_3fff`: "fake" 16550
+
A subset of the 16550 register interface is exposed. Note that, in order to
comply with the AXI4 Lite protocol mandating that reads/writes be exactly as
wide as the bus, the exposed register offsets are 4 bytes appart rather than 1
byte appart.
For more on the implementation, see the definition of `mkAXI4_Fake_16550` in
https://github.com/CTSRD-CHERI/BlueStuff/blob/master/AXI4_Fake_16550.bsv[AXI4_Fake_16550.bsv].
- `0x0000_4000 -> 0x0000_4fff`: h2f address controller
+
This device contains a single register holding the upper 32 bits to concatenate
to the 32-bit addresses used on the h2f AXI4 port to form a full 64-bit
address. The register can be written to or read back at any offset within the
exposed range.
See the definition of `mkH2FAddrCtrl` in
https://github.com/CTSRD-CHERI/DE10Pro-cheri-bgas/blob/main/bluespec/CHERI_BGAS_Top.bsv[CHERI_BGAS_Top.bsv].

== Simulation

The https://github.com/CTSRD-CHERI/DE10Pro-cheri-bgas/blob/main/bluespec/CHERI_BGAS_Top_Sim.bsv[CHERI_BGAS_Top_Sim.bsv]
file instantiates `mkCHERI_BGAS_Top` and connects it to 3 simulated DDR
memories, as well as to a set of unix fifos to bridge with other unix processes.

Running an instance of the simulator will create a folder with the following:
```sh
.
├── bgas-global-ports
│   ├── a
│   │   ├── rx
│   │   └── tx
│   ├── b
│   │   ├── rx
│   │   └── tx
│   ├── c
│   │   ├── rx
│   │   └── tx
│   └── d
│       ├── rx
│       └── tx
├── f2h
│   ├── arSource
│   ├── awSource
│   ├── bSink
│   ├── rSink
│   └── wSource
├── h2f
│   ├── arSink
│   ├── awSink
│   ├── bSource
│   ├── rSource
│   └── wSink
└── h2f_lw
    ├── arSink
    ├── awSink
    ├── bSource
    ├── rSource
    └── wSink
```
Each leaf file is a unix fifo directly connected to the relevant Bluespec module and that lets
arbitrary processes communicate with the simulated BGAS node. The f2h, h2f and h2f_lw ports
emulate the channels existing between the softlogic and the HPS system on the Stratix10. The
bgas-global-ports a, b, c and d emulate the QSFP links of the DE10 board and are meant for
node to node communication.

The provided https://github.com/CTSRD-CHERI/DE10Pro-cheri-bgas/blob/main/bluespec/sim-utils/cheri-bgas-sim.py[cheri-bgas-sim.py]
script spawns a requested number of bgas nodes as separate simulator processes as well as a splice processe per connection
between node to enable simulated communication.

The HPS <-> FPGA emulated channels enable exposing fmem devices and the debugger for a better developper
experience.

=== Build a simulator

With a working bluespec compiler, running

[source, shell]
----
$ make bluesim
----

will generate a bluesim simulator.

Once the simulator is built, one can run a simulation by using the
https://github.com/CTSRD-CHERI/DE10Pro-cheri-bgas/blob/main/bluespec/sim-utils/cheri-bgas-sim.py[cheri-bgas-sim.py]
script. The following options are available:
```sh
usage: cheri-bgas-sim.py [-h] [-t WIDTH HEIGHT] [-r SIM_RUN_DIR] [-v]

Run a CHERI-BGAS simulation

options:
  -h, --help            show this help message and exit
  -t WIDTH HEIGHT, --topology WIDTH HEIGHT
                        The WIDTH and HEIGHT of the mesh of nodes to simulate
  -r SIM_RUN_DIR, --simulation-run-directory SIM_RUN_DIR
                        The SIM_RUN_DIR path to the run directory for the simulation
  -v, --verbose         Increase verbosity level by adding more "v".
```
