default:
    @just --list

gen-bitfields:
    #!/bin/bash
    python3 ./testbenches/generate_bitfield.py > ./testbenches/include/tb_bitfields.h

sim-b name:
    make ./build/{{name}}.bsim
    ./build/{{name}}.bsim

build-v name:
    make ./build/verilog/{{name}}.v

build-sim-v name:
    make ./build/{{name}}.vsim

sim-v name:
    make ./build/{{name}}.vsim
    ./build/{{name}}.vsim

test-keymgr: (sim-v "mkSimpleIOCapKeyManager_Tb")

test-exposer-v1: (sim-v "mkSimpleIOCapExposerV1_Tb")
test-exposer-v2: (sim-v "mkSimpleIOCapExposerV2_Tb")
test-exposer-v3: (sim-v "mkSimpleIOCapExposerV3_Tb")
test-exposer-v4-noblock: (sim-v "mkSimpleIOCapExposerV4_noblock_Tb")
test-decoder-comb-11: (sim-v "mkCap2024_11_Decode_Comb_Tb")
test-decoder-comb-02: (sim-v "mkCap2024_02_Decode_Comb_Tb")
test-decoder-fsm-11: (sim-v "mkCap2024_11_Decode_FastFSM_Tb")
test-decoder-fsm-02: (sim-v "mkCap2024_02_Decode_FastFSM_Tb")

test-keymgr2-all: test-keymgr2-keydata-dualportsingle

test-keymgr2-keydata-dualportsingle: (sim-v "mkIOCapAxi_KeyManager2_KeyDataPipe_DualPortSingleCheckerPort_Tb")
test-keymgr2-refcount-twovalve: (sim-v "mkIOCapAxi_KeyManager2_RefCountPipe_TwoValve_Tb")


build-all: \
    (build-sim-v "mkSimpleIOCapKeyManager_Tb") \
    (build-sim-v "mkSimpleIOCapExposerV1_Tb") \
    (build-sim-v "mkSimpleIOCapExposerV2_Tb") \
    (build-sim-v "mkSimpleIOCapExposerV3_Tb") \
    (build-sim-v "mkSimpleIOCapExposerV4_noblock_Tb") \
    (build-sim-v "mkCap2024_11_Decode_Comb_Tb") \
    (build-sim-v "mkCap2024_02_Decode_Comb_Tb") \
    (build-sim-v "mkCap2024_11_Decode_FastFSM_Tb") \
    (build-sim-v "mkCap2024_02_Decode_FastFSM_Tb") \
    (build-sim-v "mkIOCapAxi_KeyManager2_KeyDataPipe_DualPortSingleCheckerPort_Tb") \
    (build-sim-v "mkIOCapAxi_KeyManager2_RefCountPipe_TwoValve_Tb")