
default:
    @just --list

synth:
    quartus_sh --flow compile mkCombinedIOCapExposerV6_blockinvalid_1percycle_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design

reports:
    grep -B 1 -A 6 "; Fmax Summary" output_files/mkCombinedIOCapExposerV6_blockinvalid_1percycle_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design.sta.rpt
    grep -B 1 -A 90 "; Fitter Resource Usage Summary" output_files/mkCombinedIOCapExposerV6_blockinvalid_1percycle_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design.fit.place.rpt

gui:
    quartus mkCombinedIOCapExposerV6_blockinvalid_1percycle_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design.qpf &

